
services:
  backend:
    build:
      context: ./TextTone-back 
      dockerfile: Dockerfile
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
    ports:
      - "5000:5000"
    volumes:
      - ./TextTone-back/model.keras:/app/model.keras
      - ./TextTone-back/tokenizer_sentiment.json:/app/tokenizer_sentiment.json


  frontend:
    build:
      context: .
      dockerfile: TextTone/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

